github.com:
    users:
        An0nimus85:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: An0nimus85
